name = "fp_uniforms"
prefix = "fpa"
author = "fparma"
template = "cba"
mainprefix = "z"
folder_optionals = false
sig_version = 3

check = [
    # "!link_a3"
]

postbuild = [
    # "!unlink_a3"
]

reuse_private_key = true
key_name = "fp_gear_v2"
authority = "fp_gear_v2"

[scripts.link_a3]
steps_windows = [
    "if exist a3 (rmdir a3)",
    "mklink /j a3 include\\a3"
]
steps_linux = [
    "echo 'Not supported'"
]
only_release = false
show_output = true

[scripts.unlink_a3]
steps_windows = [
    "rmdir a3"
]
steps_linux = [
    "echo 'Not supported'"
]
only_release = false
show_output = true

[version]
major = 2
minor = 0
patch = 0

[files]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]
include = [
    "*.paa"
]

